In [4]:
#pip install pandas-profiling==3.6.2

In [30]:
import pandas as pd
#from pandas_profiling import ProfileReport
pd.set_option('display.max_columns',None)
#pd.set_option('display.max_rows',None)

In [31]:
df= pd.read_csv('vdjdb.txt',sep='\t')

profile=ProfileReport(df,title='data report')

In [32]:
df.head()

complex.id gene                  cdr3       v.segm      j.segm  \
0           1  TRA         CIVRAPGRADMRF  TRAV26-1*01   TRAJ43*01   
1           1  TRB  CASSYLPGQGDHYSNQPQHF    TRBV13*01  TRBJ1-5*01   
2           0  TRB   CASSFEAGQGFFSNQPQHF    TRBV13*01  TRBJ1-5*01   
3           2  TRA        CAVPSGAGSYQLTF    TRAV20*01   TRAJ28*01   
4           2  TRB   CASSFEPGQGFYSNQPQHF    TRBV13*01  TRBJ1-5*01   

       species     mhc.a mhc.b mhc.class antigen.epitope antigen.gene  \
0  HomoSapiens  HLA-B*08   B2M      MHCI        FLKEKGGL          Nef   
1  HomoSapiens  HLA-B*08   B2M      MHCI        FLKEKGGL          Nef   
2  HomoSapiens  HLA-B*08   B2M      MHCI        FLKEKGGL          Nef   
3  HomoSapiens  HLA-B*08   B2M      MHCI        FLKEKGGL          Nef   
4  HomoSapiens  HLA-B*08   B2M      MHCI        FLKEKGGL          Nef   

  antigen.species   reference.id  \
0           HIV-1  PMID:15596521   
1           HIV-1  PMID:15596521   
2           HIV-1  PMID:15596521   
3           HIV-1  PMID:15596521   
4           HIV-1  PMID:15596521   

                                              method  \
0  {"frequency": "", "identification": "tetramer-...   
1  {"frequency": "", "identification": "tetramer-...   
2  {"frequency": "", "identification": "tetramer-...   
3  {"frequency": "", "identification": "tetramer-...   
4  {"frequency": "", "identification": "tetramer-...   

                                                meta  \
0  {"cell.subset": "CD8+", "clone.id": "", "donor...   
1  {"cell.subset": "CD8+", "clone.id": "", "donor...   
2  {"cell.subset": "CD8+", "clone.id": "", "donor...   
3  {"cell.subset": "CD8+", "clone.id": "", "donor...   
4  {"cell.subset": "CD8+", "clone.id": "", "donor...   

                                             cdr3fix  vdjdb.score web.method  \
0  {"cdr3": "CIVRAPGRADMRF", "cdr3_old": "CIVRAPG...            2       sort   
1  {"cdr3": "CASSYLPGQGDHYSNQPQHF", "cdr3_old": "...            2       sort   
2  {"cdr3": "CASSFEAGQGFFSNQPQHF", "cdr3_old": "C...            2       sort   
3  {"cdr3": "CAVPSGAGSYQLTF", "cdr3_old": "CAVPSG...            2       sort   
4  {"cdr3": "CASSFEPGQGFYSNQPQHF", "cdr3_old": "C...            2       sort   

  web.method.seq web.cdr3fix.nc web.cdr3fix.unmp  
0         sanger             no               no  
1         sanger             no               no  
2         sanger             no               no  
3         sanger             no               no  
4         sanger             no               no

In [33]:
#df1=df[['antigen.epitope','antigen.gene','antigen.species']]

proof reference for the making the HIV and HIV-1 and HIV1 are the same 
 - https://www.aidsmap.com/about-hiv/hiv-1-and-hiv-2#:~:text=HIV%2D1%20comprises%20groups%20M,2%20subtypes%2C%20A%20and%20B.&text=Due%20to%20the%20genetic%20difference,not%20reliably%20detect%20HIV%2D2.
 - https://www.frontiersin.org/articles/10.3389/fimmu.2019.02820/full(Using random forest)

In [60]:
df['antigen.species'].unique()

array(['HIV-1', 'TriticumAestivum', 'CMV', 'SARS-CoV-2', 'HomoSapiens',
       'EBV', 'M.tuberculosis', 'HTLV-1', 'GallusGallus', 'MusMusculus',
       'InfluenzaA', 'Synthetic', 'VSV', 'SaccharomycesCerevisiae',
       'ManducaSexta', 'HCV', 'synthetic', 'E.Coli', 'HHV', 'LCMV',
       'DENV1', 'DENV3/4', 'PlasmodiumBerghei',
       'SelaginellaMoellendorffii', 'PseudomonasFluorescens',
       'PseudomonasAeruginosa', 'HIV1', 'Homo sapiens', 'YFV', 'RSV',
       'HSV-2', 'DENV2', 'HPV-16', 'MCMV', 'MCPyV', 'HPV',
       'StreptomycesKanamyceticus', 'Wheat', 'HIV', 'HCoV-HKU1', 'SIV',
       'AdV'], dtype=object)

df2=df.copy()
for i in range(0,len(df1)):
    j=df2['antigen.species'][i]
    if j == 'HIV1' or j=='HIV':
        df2['antigen.species'][i]='HIV-1'

Since the there only 2 distint values in "Gene" variable, we will be implementing 1 hot encoding  

In [61]:
df2.columns

Index(['complex.id', 'gene', 'cdr3', 'v.segm', 'j.segm', 'species', 'mhc.a',
       'mhc.b', 'mhc.class', 'antigen.epitope', 'antigen.gene',
       'antigen.species', 'reference.id', 'method', 'meta', 'cdr3fix',
       'vdjdb.score', 'web.method', 'web.method.seq', 'web.cdr3fix.nc',
       'web.cdr3fix.unmp'],
      dtype='object')

In [70]:
cdr_sequence=pd.DataFrame()

In [71]:
cdr_sequence=df2['cdr3']

In [72]:
amino_acids = [cdr_sequence[i:i+3] for i in range(0, len(cdr_sequence), 3)]

pandas.core.series.Series

In [74]:
cdr_sequence.join(amino_acids)

AttributeError: 'Series' object has no attribute 'join'

In [58]:
Encoded_df= pd.get_dummies(df2,dtype='int',columns=['gene', 'species'])

In [59]:
Encoded_df

complex.id                  cdr3       v.segm      j.segm  \
0               1         CIVRAPGRADMRF  TRAV26-1*01   TRAJ43*01   
1               1  CASSYLPGQGDHYSNQPQHF    TRBV13*01  TRBJ1-5*01   
2               0   CASSFEAGQGFFSNQPQHF    TRBV13*01  TRBJ1-5*01   
3               2        CAVPSGAGSYQLTF    TRAV20*01   TRAJ28*01   
4               2   CASSFEPGQGFYSNQPQHF    TRBV13*01  TRBJ1-5*01   
...           ...                   ...          ...         ...   
92766       30592       CASSPGQGGDNEQFF   TRBV7-3*01  TRBJ2-1*01   
92767       30593          CAPQGATNKLIF  TRAV12-2*01   TRAJ32*01   
92768       30593       CASSLGAGGQETQYF   TRBV5-1*01  TRBJ2-5*01   
92769       30594        CLVGGSGGYNKLIF     TRAV4*01    TRAJ4*01   
92770       30594         CASSSTAQETQYF  TRBV11-2*01  TRBJ2-5*01   

                mhc.a           mhc.b mhc.class antigen.epitope antigen.gene  \
0            HLA-B*08             B2M      MHCI        FLKEKGGL          Nef   
1            HLA-B*08             B2M      MHCI        FLKEKGGL          Nef   
2            HLA-B*08             B2M      MHCI        FLKEKGGL          Nef   
3            HLA-B*08             B2M      MHCI        FLKEKGGL          Nef   
4            HLA-B*08             B2M      MHCI        FLKEKGGL          Nef   
...               ...             ...       ...             ...          ...   
92766  HLA-DQA1*05:01  HLA-DQB1*02:01     MHCII   PQQPFPQPEQPFP       Gluten   
92767  HLA-DQA1*05:01  HLA-DQB1*02:01     MHCII   PQQPFPQPEQPFP       Gluten   
92768  HLA-DQA1*05:01  HLA-DQB1*02:01     MHCII   PQQPFPQPEQPFP       Gluten   
92769  HLA-DQA1*05:01  HLA-DQB1*02:01     MHCII   PQQPFPQPEQPFP       Gluten   
92770  HLA-DQA1*05:01  HLA-DQB1*02:01     MHCII   PQQPFPQPEQPFP       Gluten   

      antigen.species   reference.id  \
0               HIV-1  PMID:15596521   
1               HIV-1  PMID:15596521   
2               HIV-1  PMID:15596521   
3               HIV-1  PMID:15596521   
4               HIV-1  PMID:15596521   
...               ...            ...   
92766           Wheat  PMID:33927715   
92767           Wheat  PMID:33927715   
92768           Wheat  PMID:33927715   
92769           Wheat  PMID:33927715   
92770           Wheat  PMID:33927715   

                                                  method  \
0      {"frequency": "", "identification": "tetramer-...   
1      {"frequency": "", "identification": "tetramer-...   
2      {"frequency": "", "identification": "tetramer-...   
3      {"frequency": "", "identification": "tetramer-...   
4      {"frequency": "", "identification": "tetramer-...   
...                                                  ...   
92766  {"frequency": "", "identification": "tetramer-...   
92767  {"frequency": "", "identification": "tetramer-...   
92768  {"frequency": "", "identification": "tetramer-...   
92769  {"frequency": "", "identification": "tetramer-...   
92770  {"frequency": "", "identification": "tetramer-...   

                                                    meta  \
0      {"cell.subset": "CD8+", "clone.id": "", "donor...   
1      {"cell.subset": "CD8+", "clone.id": "", "donor...   
2      {"cell.subset": "CD8+", "clone.id": "", "donor...   
3      {"cell.subset": "CD8+", "clone.id": "", "donor...   
4      {"cell.subset": "CD8+", "clone.id": "", "donor...   
...                                                  ...   
92766  {"cell.subset": "CD4+", "clone.id": "", "donor...   
92767  {"cell.subset": "CD4+", "clone.id": "", "donor...   
92768  {"cell.subset": "CD4+", "clone.id": "", "donor...   
92769  {"cell.subset": "CD4+", "clone.id": "", "donor...   
92770  {"cell.subset": "CD4+", "clone.id": "", "donor...   

                                                 cdr3fix  vdjdb.score  \
0      {"cdr3": "CIVRAPGRADMRF", "cdr3_old": "CIVRAPG...            2   
1      {"cdr3": "CASSYLPGQGDHYSNQPQHF", "cdr3_old": "...            2   
2      {"cdr3": "CASSFEAGQGFFSNQPQHF", "cdr3_old": "C...            2   
3      {"cdr3"

In [79]:
import numpy as np

# Define the amino acid alphabet
amino_acid_alphabet = 'ACDEFGHIKLMNPQRSTVWY'

def cdr_to_one_hot(cdr_sequence):
    one_hot_encoding = np.zeros((len(cdr_sequence), len(amino_acid_alphabet)))

    for i, amino_acid in enumerate(cdr_sequence):
        #print(i,amino_acid)
        if amino_acid in amino_acid_alphabet:
            index = amino_acid_alphabet.index(amino_acid)
            one_hot_encoding[i, index] = 1

    return one_hot_encoding

# Example CDR sequence
cdr_sequence = "CASSYLPGQGDHYSNQPQHF"

# Convert CDR sequence to one-hot representation
one_hot_representation = cdr_to_one_hot(cdr_sequence)

# Display the result
print("CDR Sequence:", cdr_sequence)
print("One-Hot Representation:")
print(one_hot_representation)

CDR Sequence: CASSYLPGQGDHYSNQPQHF
One-Hot Representation:
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 